baseURL = 'https://threestone.top/'
defaultContentLanguage = 'zh-cn'
title = '岩的日志'
theme = 'blowfish'
hasCJKLanguage = true
[params]
  description = '成长和生活'
[menus]
  [[menus.main]]
    name = '全部文章'
    pageRef = 'posts'
    weight = 20
